-- טבלת משימות
create table tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    type text not null,
    description text,
    due_date date,
    subtasks jsonb default '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- טבלת מלאי והזמנות
create table inventory (
    id bigint generated by default as identity primary key,
    item_name text not null,
    quantity integer not null default 0,
    supplier text,
    price numeric(10,2),
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- טבלת מעקב ציוד
create table equipment_tracking (
    id bigint generated by default as identity primary key,
    item_name text not null,
    checkout_date date not null,
    return_date date,
    staff_member text not null,
    borrower_name text not null,
    borrower_signature text,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- טבלת אירועי חינוך בלתי פורמלי
create table events (
    id bigint generated by default as identity primary key,
    title text not null,
    start_date date not null,
    end_date date,
    type text not null,
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- טבלת חופשות ומועדי משרד החינוך
create table education_dates (
    id bigint generated by default as identity primary key,
    title text not null,
    start_date date not null,
    end_date date not null,
    type text not null,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
