-- טבלת אירועי מחלקה
create table if not exists department_events (
  id bigint primary key generated by default as identity,
  title text not null,
  description text,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  type text default 'אירוע מחלקה',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- הרשאות RLS
alter table department_events enable row level security;

create policy "Enable read access for all users"
  on department_events for select
  using (true);

create policy "Enable insert for authenticated users only"
  on department_events for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only"
  on department_events for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only"
  on department_events for delete
  using (auth.role() = 'authenticated');

-- אינדקסים
create index if not exists department_events_start_date_idx on department_events(start_date);
create index if not exists department_events_end_date_idx on department_events(end_date);
