-- טבלת חופשות וחגים
create table if not exists education_dates (
  id bigint primary key generated by default as identity,
  title text not null,
  description text,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  type text default 'חופשה',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- הרשאות RLS
alter table education_dates enable row level security;

create policy "Enable read access for all users"
  on education_dates for select
  using (true);

create policy "Enable insert for authenticated users only"
  on education_dates for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only"
  on education_dates for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only"
  on education_dates for delete
  using (auth.role() = 'authenticated');

-- אינדקסים
create index if not exists education_dates_start_date_idx on education_dates(start_date);
create index if not exists education_dates_end_date_idx on education_dates(end_date);
