-- טבלת חופשות וחגים
create table if not exists education_dates (
  id bigint primary key generated by default as identity,
  title text not null,
  description text,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  type text default 'חופשה',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- הרשאות RLS
alter table education_dates enable row level security;

create policy "Enable read access for all users"
  on education_dates for select
  using (true);

create policy "Enable insert for authenticated users only"
  on education_dates for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only"
  on education_dates for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only"
  on education_dates for delete
  using (auth.role() = 'authenticated');

-- אינדקסים
create index if not exists education_dates_start_date_idx on education_dates(start_date);
create index if not exists education_dates_end_date_idx on education_dates(end_date);

-- מחיקת נתונים קיימים
delete from education_dates;

-- הוספת נתונים חדשים
insert into education_dates (title, start_date, end_date, type, description) values
  ('ראש השנה', '2024-10-02', '2024-10-04', 'חג', 'חזרה ללימודים: 6 באוקטובר 2024'),
  ('יום כיפור', '2024-10-11', '2024-10-12', 'חג', 'חזרה ללימודים: 13 באוקטובר 2024'),
  ('חופשת סוכות', '2024-10-13', '2024-10-24', 'חופשה', 'חזרה ללימודים: 25 באוקטובר 2024'),
  ('חנוכה', '2024-12-27', '2025-01-02', 'חג', 'חזרה ללימודים: 3 בינואר 2025'),
  ('פורים', '2025-03-14', '2025-03-16', 'חג', 'חזרה ללימודים: 17 במרץ 2025'),
  ('חופשת פסח', '2025-04-04', '2025-04-19', 'חופשה', 'חזרה ללימודים: 20 באפריל 2025'),
  ('יום העצמאות', '2025-05-01', '2025-05-01', 'חג', 'חזרה ללימודים: 2 במאי 2025'),
  ('שבועות', '2025-06-01', '2025-06-02', 'חג', 'חזרה ללימודים: 3 ביוני 2025'),
  ('סיום שנת הלימודים - חטיבות ביניים ובתי ספר על-יסודיים (5 ימי לימוד)', '2025-06-19', '2025-06-19', 'סיום לימודים', null),
  ('סיום שנת הלימודים - חטיבות ביניים ובתי ספר על-יסודיים (6 ימי לימוד)', '2025-06-20', '2025-06-20', 'סיום לימודים', null),
  ('סיום שנת הלימודים - גני ילדים ובתי ספר יסודיים', '2025-06-30', '2025-06-30', 'סיום לימודים', null);
