-- Create folders table
create table form_folders (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table form_folders enable row level security;

-- Create storage bucket for form files
insert into storage.buckets (id, name, public) values ('forms', 'forms', false);

-- Create policies for form_folders table
create policy "Enable read access for all users"
    on form_folders for select
    using (true);

create policy "Enable insert for all users"
    on form_folders for insert
    with check (true);

create policy "Enable delete for all users"
    on form_folders for delete
    using (true);

-- Create policies for storage
create policy "Enable read access for all users"
    on storage.objects for select
    using (bucket_id = 'forms');

create policy "Enable insert for all users"
    on storage.objects for insert
    with check (bucket_id = 'forms');

create policy "Enable delete for all users"
    on storage.objects for delete
    using (bucket_id = 'forms');
