-- Create form_folders table
create table form_folders (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security)
alter table form_folders enable row level security;

-- Create policy to allow all users to view folders
create policy "Allow users to view folders"
  on form_folders for select
  to authenticated
  using (true);

-- Create policy to allow only admins to create/update/delete folders
create policy "Allow admins to manage folders"
  on form_folders for all
  to authenticated
  using (auth.role() = 'admin');

-- Create storage bucket for forms
insert into storage.buckets (id, name, public) values ('forms', 'forms', false);

-- Create storage policy to allow all users to view files
create policy "Allow users to view files"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'forms');

-- Create storage policy to allow only admins to upload/delete files
create policy "Allow admins to manage files"
  on storage.objects for all
  to authenticated
  using (bucket_id = 'forms' and auth.role() = 'admin');
